import playwright from 'eslint-plugin-playwright';
import tseslint from 'typescript-eslint';

/**
 * Guardrails for tests an agent wrote.
 *
 * The point is not style. Every rule below is switched to `error` because it
 * catches a specific way an agent produces a test that looks fine, passes CI,
 * and checks nothing.
 *
 * The first one is the reason this file exists. Playwright's own healer agent
 * definition (.claude/agents/playwright-test-healer.md, generated by
 * `playwright init-agents`, not written by me) ends with:
 *
 *   "If the error persists and you have high level of confidence that the test
 *    is correct, mark this test as test.fixme() so that it is skipped during
 *    the execution."
 *
 * So the officially shipped agent is told it may silence a test it cannot fix,
 * and it is told to "do the most reasonable thing possible to pass the test".
 * A healer that turns red into skipped has made the suite green and the product
 * no safer. `disallowFixme` closes that door: the healer must actually fix the
 * test, or leave it failing where a human can see it.
 */
const agentGuardrails = {
	// The healer's escape hatch — skip and fixme both banned.
	'playwright/no-skipped-test': [ 'error', { disallowFixme: true } ],

	// A stray .only() silently reduces the suite to one test while staying green.
	'playwright/no-focused-test': 'error',

	// A test with no assertion cannot fail. Agents produce these when a step
	// "worked" and they forget the test has to prove something.
	'playwright/expect-expect': 'error',

	// An assertion that can never fail is worse than none, because it reads as
	// coverage.
	'playwright/no-unnecessary-assertions': 'error',

	// expect() inside if/try/catch: the branch never runs, the test passes.
	'playwright/no-conditional-expect': 'error',
	'playwright/no-conditional-in-test': 'error',

	// Commenting a test out is the quiet version of deleting it.
	'playwright/no-commented-out-tests': 'error',

	// Fixed sleeps are the default way an agent "fixes" a race. They convert a
	// real failure into a slow, intermittent one.
	'playwright/no-wait-for-timeout': 'error',

	// Verified by hand on this app: networkidle never settles here, so a test
	// waiting on it hangs until timeout. Playwright's own healer prompt forbids
	// it too — this makes the ban enforceable instead of advisory.
	'playwright/no-networkidle': 'error',

	// Web-first assertions retry; a bare truthiness check on a resolved value
	// does not, and becomes flaky under load.
	'playwright/prefer-web-first-assertions': 'error',
	'playwright/missing-playwright-await': 'error',

	// nth(0)/first() on an unscoped locator quietly asserts about "whichever
	// element happened to come back first".
	'playwright/no-element-handle': 'error',
	'playwright/no-eval': 'error',
	'playwright/no-page-pause': 'error'
};

export default [
	{
		ignores: [ 'node_modules/**', 'test-results/**', 'playwright-report/**', 'reports/**', 'tests/guardrails/**' ]
	},

	{
		files: [ 'tests/**/*.ts', 'scripts/**/*.ts' ],
		languageOptions: {
			parser: tseslint.parser,
			ecmaVersion: 'latest',
			sourceType: 'module'
		},
		plugins: { playwright },
		rules: {
			...playwright.configs[ 'flat/recommended' ].rules,
			...agentGuardrails,

			// Deliberately off. Product and category elements embed a ULID that
			// changes on every database reseed, so `[data-test^="product-"]` is the
			// reseed-proof way to reach them. Banning raw locators here would push
			// tests towards hardcoding a ULID, which is the failure this repo is
			// trying to prevent.
			'playwright/no-raw-locators': 'off'
		}
	}
];
